#!/usr/bin/env python3
# SPDX-License-Identifier: CDDL-1.0
# Copyright (c) 2020, 2021 Daniel Washburn <daniel@washburn.at>

from hex2words import hex2words
from secrets import token_hex
import sys

def main(argv):
    try:
        names = int(argv[1])
    except:
        names = 1
    try:
        nbytes = int(argv[2])
    except:
        nbytes = 2

    for i in range(names):
        tok = token_hex(nbytes)
        print("_".join(hex2words.hex2words(tok).lower().split()))

if __name__ == "__main__":
    main(sys.argv)
