#!/usr/bin/env python3
# SPDX-License-Identifier: CDDL-1.0
# Copyright (c) 2020 Daniel Washburn <daniel@washburn.at>

from hex2words import hex2words
from secrets import token_hex
import sys

def main(argv):
    try:
        num = int(argv[1])
    except:
        num = 1

    for i in range(num):
        tok = token_hex(2)
        print("_".join(hex2words.hex2words(tok).lower().split()))

if __name__ == "__main__":
    main(sys.argv)
